config/routes.rb
Rails.application.routes.draw do
  resources :histories
  resources :dependents
  root 'home#index'
  get "sessions/user", "sessions#user"
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  delete 'logout', to: 'sessions#destroy', as: 'logout'
  get "users/:user_id/dependents", to: "dependents#get_for_user" 
  get "histories/user/:user_id", to: "histories#get_for_user"
  get "histories/user/:user_id/current", to: "histories#get_for_user_current"
  put "session/update_password", to: "sessions#update_password"
  # get 'signup', to: 'users#new', as: 'signup'
  # get 'login', to: 'sessions#new', as: 'login'
  #get 'logout', to: 'sessions#destroy', as: 'logout'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/dependent.rb
class Dependent < ApplicationRecord
    belongs_to :user
    has_many :histories
    validates :name, presence: true
    validates :relationship, presence: true
    validates :email, presence: true
end

app/controllers/dependents_controller.rb
class DependentsController < ApplicationController
  before_action :set_dependent, only: [:show, :edit, :update, :destroy]

  # GET /dependents
  # GET /dependents.json
  def index
    @dependents = Dependent.all
  end
  #GET /users/:user_id/dependents
  def get_for_user
    user_id = params[:user_id]
    @dependents = Dependent
          .where(user_id: user_id)

    render json: @dependents
  end
  # GET /dependents/1
  # GET /dependents/1.json
  def show
  end

  # GET /dependents/new
  def new
    @dependent = Dependent.new
  end

  # GET /dependents/1/edit
  def edit
  end

  # POST /dependents
  # POST /dependents.json
  def create
    @dependent = Dependent.new(dependent_params)

    respond_to do |format|
      if @dependent.save
        format.html { redirect_to @dependent, notice: 'Dependent was successfully created.' }
        format.json { render :show, status: :created, location: @dependent }
      else
        format.html { render :new }
        format.json { render json: @dependent.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dependents/1
  # PATCH/PUT /dependents/1.json
  def update
    respond_to do |format|
      if @dependent.update(dependent_params)
        format.html { redirect_to @dependent, notice: 'Dependent was successfully updated.' }
        format.json { render :show, status: :ok, location: @dependent }
      else
        format.html { render :edit }
        format.json { render json: @dependent.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dependents/1
  # DELETE /dependents/1.json
  def destroy
    @dependent.destroy
    respond_to do |format|
      format.html { redirect_to dependents_url, notice: 'Dependent was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dependent
      @dependent = Dependent.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def dependent_params
      params.require(:dependent).permit(:relationship, :name, :email, :contact, :dob, :blood_group, :height, :weight, :user_id)
    end
end

app/helpers/dependents_helper.rb
module DependentsHelper
end

app/views/dependents/_form.html.erb
<%= form_with(model: dependent, local: true) do |form| %>
  <% if dependent.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(dependent.errors.count, "error") %> prohibited this dependent from being saved:</h2>

      <ul>
        <% dependent.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :relationship %>
    <%= form.text_field :relationship %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :contact %>
    <%= form.text_field :contact %>
  </div>

  <div class="field">
    <%= form.label :dob %>
    <%= form.date_select :dob %>
  </div>

  <div class="field">
    <%= form.label :blood_group %>
    <%= form.text_field :blood_group %>
  </div>

  <div class="field">
    <%= form.label :height %>
    <%= form.number_field :height %>
  </div>

  <div class="field">
    <%= form.label :weight %>
    <%= form.number_field :weight %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/dependents/edit.html.erb
<h1>Editing Dependent</h1>

<%= render 'form', dependent: @dependent %>

<%= link_to 'Show', @dependent %> |
<%= link_to 'Back', dependents_path %>

app/views/dependents/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Dependents</h1>

<table>
  <thead>
    <tr>
      <th>Relationship</th>
      <th>Name</th>
      <th>Email</th>
      <th>Contact</th>
      <th>Dob</th>
      <th>Blood group</th>
      <th>Height</th>
      <th>Weight</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dependents.each do |dependent| %>
      <tr>
        <td><%= dependent.relationship %></td>
        <td><%= dependent.name %></td>
        <td><%= dependent.email %></td>
        <td><%= dependent.contact %></td>
        <td><%= dependent.dob %></td>
        <td><%= dependent.blood_group %></td>
        <td><%= dependent.height %></td>
        <td><%= dependent.weight %></td>
        <td><%= link_to 'Show', dependent %></td>
        <td><%= link_to 'Edit', edit_dependent_path(dependent) %></td>
        <td><%= link_to 'Destroy', dependent, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dependent', new_dependent_path %>

app/views/dependents/new.html.erb
<h1>New Dependent</h1>

<%= render 'form', dependent: @dependent %>

<%= link_to 'Back', dependents_path %>

app/views/dependents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Relationship:</strong>
  <%= @dependent.relationship %>
</p>

<p>
  <strong>Name:</strong>
  <%= @dependent.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @dependent.email %>
</p>

<p>
  <strong>Contact:</strong>
  <%= @dependent.contact %>
</p>

<p>
  <strong>Dob:</strong>
  <%= @dependent.dob %>
</p>

<p>
  <strong>Blood group:</strong>
  <%= @dependent.blood_group %>
</p>

<p>
  <strong>Height:</strong>
  <%= @dependent.height %>
</p>

<p>
  <strong>Weight:</strong>
  <%= @dependent.weight %>
</p>

<%= link_to 'Edit', edit_dependent_path(@dependent) %> |
<%= link_to 'Back', dependents_path %>