config/routes.rb
Rails.application.routes.draw do
  resources :histories
  resources :dependents
  root 'home#index'
  get "sessions/user", "sessions#user"
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  delete 'logout', to: 'sessions#destroy', as: 'logout'
  get "users/:user_id/dependents", to: "dependents#get_for_user" 
  get "histories/user/:user_id", to: "histories#get_for_user"
  get "histories/user/:user_id/current", to: "histories#get_for_user_current"
  put "session/update_password", to: "sessions#update_password"
  # get 'signup', to: 'users#new', as: 'signup'
  # get 'login', to: 'sessions#new', as: 'login'
  #get 'logout', to: 'sessions#destroy', as: 'logout'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/history.rb
class History < ApplicationRecord
    belongs_to :user
    belongs_to :dependent, optional: true
    validates :illness, presence: true
    validates :doctor, presence: true
    validates :medicines, presence: true
    validates :start_date, presence: true
    validates :end_date, presence: true
end

app/controllers/histories_controller.rb
class HistoriesController < ApplicationController
  before_action :set_history, only: [:show, :edit, :update, :destroy]

  # GET /histories
  # GET /histories.json
  def index
    @histories = History.all
  end

  # GET /histories/1
  # GET /histories/1.json
  def show
  end

  # GET /histories/new
  def new
    @history = History.new
  end

  # GET /histories/1/edit
  def edit
  end

  #GET "histories/user/:user_id"
  def get_for_user
    user_id = params[:user_id]

    # # for today
    # @medical_histories = MedicalHistory
          # .where(user_id: user_id, dependent_id: nil)
          # .where("? BETWEEN startdate AND enddate", DateTime.now.to_date)
          # .order(:startdate, :asc)

    # # if no records for today, then get for tomorrow
    # if @medical_histories.size == 0 
    #   @medical_histories = MedicalHistory
    #   .where(user_id: user_id, dependent_id: nil)
    #   .where("? BETWEEN startdate AND enddate",  DateTime.now.next_day.to_date)
    #   .order(:startdate, :asc) 
    # end
    @histories = History.where(user_id: user_id)
          .order(:start_date, :asc)
          
    render json: @histories
  end

  #GET "histories/user/:user_id/current"
  def get_for_user_current
    user_id = params[:user_id]

    # for today
    @histories = History
           .where(user_id: user_id)
           .where("? BETWEEN start_date AND end_date", DateTime.now.to_date)
           .order(:start_date, :asc)

    # if no records for today, then get for tomorrow
    if @histories.size == 0 
      @histories = History
      .where(user_id: user_id)
      .where("? BETWEEN start_date AND end_date",  DateTime.now.next_day.to_date)
      .order(:start_date, :asc) 
    end 
    render json: @histories
  end


  # POST /histories
  # POST /histories.json
  def create
    @history = History.new(history_params)

    respond_to do |format|
      if @history.save
        format.html { redirect_to @history, notice: 'History was successfully created.' }
        format.json { render :show, status: :created, location: @history }
      else
        format.html { render :new }
        format.json { render json: @history.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /histories/1
  # PATCH/PUT /histories/1.json
  def update
    respond_to do |format|
      if @history.update(history_params)
        format.html { redirect_to @history, notice: 'History was successfully updated.' }
        format.json { render :show, status: :ok, location: @history }
      else
        format.html { render :edit }
        format.json { render json: @history.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /histories/1
  # DELETE /histories/1.json
  def destroy
    @history.destroy
    respond_to do |format|
      format.html { redirect_to histories_url, notice: 'History was successfully destroyed.' }
      format.json {render json: {'record': "Deleted"},
                    status: :ok}
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_history
      @history = History.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def history_params
      params.require(:history).permit(:illness, :doctor, :medicines, :start_date, :end_date, :dosage_amount, :dosage_frequency, :dosage_time, :notification, :user_id,:dependent_id)
    end
end

app/helpers/histories_helper.rb
module HistoriesHelper
end

app/views/histories/_form.html.erb
<%= form_with(model: history, local: true) do |form| %>
  <% if history.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(history.errors.count, "error") %> prohibited this history from being saved:</h2>

      <ul>
        <% history.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :illness %>
    <%= form.text_field :illness %>
  </div>

  <div class="field">
    <%= form.label :doctor %>
    <%= form.text_field :doctor %>
  </div>

  <div class="field">
    <%= form.label :medicines %>
    <%= form.text_field :medicines %>
  </div>

  <div class="field">
    <%= form.label :start_date %>
    <%= form.date_select :start_date %>
  </div>

  <div class="field">
    <%= form.label :end_date %>
    <%= form.date_select :end_date %>
  </div>

  <div class="field">
    <%= form.label :dosage_amount %>
    <%= form.number_field :dosage_amount %>
  </div>

  <div class="field">
    <%= form.label :dosage_frequency %>
    <%= form.number_field :dosage_frequency %>
  </div>

  <div class="field">
    <%= form.label :dosage_time %>
    <%= form.time_select :dosage_time %>
  </div>

  <div class="field">
    <%= form.label :notification %>
    <%= form.check_box :notification %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/histories/edit.html.erb
<h1>Editing History</h1>

<%= render 'form', history: @history %>

<%= link_to 'Show', @history %> |
<%= link_to 'Back', histories_path %>

app/views/histories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Histories</h1>

<table>
  <thead>
    <tr>
      <th>Illness</th>
      <th>Doctor</th>
      <th>Medicines</th>
      <th>Start date</th>
      <th>End date</th>
      <th>Dosage amount</th>
      <th>Dosage frequency</th>
      <th>Dosage time</th>
      <th>Notification</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @histories.each do |history| %>
      <tr>
        <td><%= history.illness %></td>
        <td><%= history.doctor %></td>
        <td><%= history.medicines %></td>
        <td><%= history.start_date %></td>
        <td><%= history.end_date %></td>
        <td><%= history.dosage_amount %></td>
        <td><%= history.dosage_frequency %></td>
        <td><%= history.dosage_time %></td>
        <td><%= history.notification %></td>
        <td><%= link_to 'Show', history %></td>
        <td><%= link_to 'Edit', edit_history_path(history) %></td>
        <td><%= link_to 'Destroy', history, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New History', new_history_path %>

app/views/histories/new.html.erb
<h1>New History</h1>

<%= render 'form', history: @history %>

<%= link_to 'Back', histories_path %>

app/views/histories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Illness:</strong>
  <%= @history.illness %>
</p>

<p>
  <strong>Doctor:</strong>
  <%= @history.doctor %>
</p>

<p>
  <strong>Medicines:</strong>
  <%= @history.medicines %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @history.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @history.end_date %>
</p>

<p>
  <strong>Dosage amount:</strong>
  <%= @history.dosage_amount %>
</p>

<p>
  <strong>Dosage frequency:</strong>
  <%= @history.dosage_frequency %>
</p>

<p>
  <strong>Dosage time:</strong>
  <%= @history.dosage_time %>
</p>

<p>
  <strong>Notification:</strong>
  <%= @history.notification %>
</p>

<%= link_to 'Edit', edit_history_path(@history) %> |
<%= link_to 'Back', histories_path %>